### ISSUE TITLE
Text rendering issue on Windows 10

### ISSUE THREAD

**Issue by r1chardj0n3s** [lordmauve/gamemaths#2]
I don't know why, but the text doesn't come out right on Windows :(
![font-or-encoding-issue](https://user-images.githubusercontent.com/663366/80277715-42622980-8734-11ea-8912-fc734d89adde.png)

**Comment by lordmauve** [comment]
Woah... is that when running it directly, or via `presentation.py`?

**Comment by lordmauve** [comment]
I've annotated all the source as UTF-8 and specified the encoding explicitly in presentation.py. Does that help?

**Comment by r1chardj0n3s** [comment]
Yeah!!! Solved :)
